default: runProgram


BookMapper.class: BookMapper.java
	javac BookMapper.java


runProgram: BookMapper.class
	java BookMapper

test:
BackendDeveloperTest.class: BackendDeveloperTest.java
	javac BackendDeveloperTest.java
test: BackendDeveloperTest.class
	java BackendDeveloperTest

clean:
	rm *.class